language: android
android:
  components:
    - build-tools-27.0.3
    - tools
    - platform-tools
    - android-27
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - cd Android
  - chmod +x gradlew

script:
  - ./gradlew assemble
